# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grabbags', '0001_initial'),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grabbag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabbags.Grabbag')),
                ('grabbag_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabbag_giver', to=settings.AUTH_USER_MODEL)),
                ('grabbag_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabbag_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gift_assignment',
            },
        ),
    ]
