# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
