# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
        ('grabbags', '0001_initial'),
        ('users', '0002_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift')),
                ('grabbag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabbags.Grabbag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_gift',
            },
        ),
    ]
